#! /bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc monitor -d I II III IV V VI VII VIII IX

feh --bg-fill /home/skye/Pictures/wp/obey.png

/home/skye/.config/lemonbar/bar.sh | lemonbar -p
