#!/bin/bash

RED="\e[31m"
GRN="\e[32m"
BLU="\e[34m"
RES="\e[0m"

fail() {
	printf "$RED FAIL $RES"
	exit 1
}

if [[ -z $1 ]]; then
	printf "$RED[wcon] $RES::$RED ERROR$RES Please enter the name of a configuration file\n"
	exit 1
fi
printf "$GRN[wcon] $RES:: Killing internet..."
sudo killall wpa_supplicant dhcpcd
printf "OK\n"

printf "$GRN[wcon] $RES::$BLU Starting wpa_supplicant with conf file '/etc/wpa/$1.conf'...$RES"
sudo wpa_supplicant -B -Dnl80211 -iwlo1 -c/etc/wpa/$1.conf
echo -e "$GRN OK$RES"
printf "$GRN[wcon] $RES::$BLU Running dhcpcd...\n$RES"
sudo dhcpcd &> /dev/null || fail
echo -e "$GRN OK$RES"
